package ws

import (
	"fmt"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
)

type llamaFleetScanResult struct {
	Machine struct {
		CPUCores  int `json:"cpuCores"`
		MemoryGiB int `json:"memoryGiB"`
	} `json:"machine"`
	Recommendation struct {
		BasePort     int `json:"basePort"`
		Backends     int `json:"backends"`
		Parallel     int `json:"parallel"`
		Threads      int `json:"threads"`
		ThreadsBatch int `json:"threadsBatch"`
		ThreadsHTTP  int `json:"threadsHttp"`
		Ctx          int `json:"ctx"`
		Batch        int `json:"batch"`
		UBatch       int `json:"ubatch"`
	} `json:"recommendation"`
	EnvPreview   string   `json:"envPreview"`
	WroteEnvFile bool     `json:"wroteEnvFile,omitempty"`
	EnvFilePath  string   `json:"envFilePath,omitempty"`
	Notes        []string `json:"notes"`
}

// runLlamaFleetScan detects system capabilities and recommends optimal llama.cpp fleet settings.
func runLlamaFleetScan(projectPath string, writeFile bool) (llamaFleetScanResult, error) {
	cpuCores := runtime.NumCPU()
	if cpuCores < 1 {
		cpuCores = 1
	}
	memGiB := detectSystemMemoryGiB()

	// Reserve budget for desktop/editor and non-inference tasks.
	cpuBudget := maxInt(1, cpuCores-2)
	memoryBudget := maxInt(4, memGiB-4)

	modelEstimateGiB := parsePositiveIntEnv("LLAMA_MODEL_EST_GIB", 4)
	if modelEstimateGiB < 2 {
		modelEstimateGiB = 2
	}

	maxBackendsByMemory := maxInt(1, memoryBudget/modelEstimateGiB)
	maxBackendsByCPU := maxInt(1, cpuBudget/4)
	maxBackends := minInt(8, minInt(maxBackendsByMemory, maxBackendsByCPU))
	if maxBackends < 1 {
		maxBackends = 1
	}

	bestScore := -1.0
	bestBackends := 1
	bestParallel := 1
	bestThreads := 2
	bestBatch := 256
	bestUBatch := 64

	batchCandidates := []int{256, 384, 512}
	ubatchCandidates := []int{64, 128}

	// Sequentially evaluate candidate fleet layouts; prefer high throughput under
	// strict CPU/memory efficiency constraints.
	for backends := 1; backends <= maxBackends; backends++ {
		threads := clampInt(cpuBudget/backends, 2, 8)
		maxParallel := clampInt((cpuBudget/backends)/2, 1, 4)
		for parallel := 1; parallel <= maxParallel; parallel++ {
			for _, batch := range batchCandidates {
				for _, ubatch := range ubatchCandidates {
					if ubatch > batch {
						continue
					}
					workerDemand := float64(backends * threads)
					cpuEff := minFloat(1.0, float64(cpuBudget)/maxFloat(1.0, workerDemand))
					memDemand := float64(backends * modelEstimateGiB)
					memEff := minFloat(1.0, float64(memoryBudget)/maxFloat(1.0, memDemand))
					throughput := float64(backends*parallel) * math.Sqrt(float64(batch))
					score := throughput * cpuEff * memEff
					if score > bestScore {
						bestScore = score
						bestBackends = backends
						bestParallel = parallel
						bestThreads = threads
						bestBatch = batch
						bestUBatch = ubatch
					}
				}
			}
		}
	}

	basePort := parsePositiveIntEnv("LLAMA_BASE_PORT", 8081)
	ctx := 8192
	if memoryBudget >= 24 {
		ctx = 16384
	}

	var result llamaFleetScanResult
	result.Machine.CPUCores = cpuCores
	result.Machine.MemoryGiB = memGiB
	result.Recommendation.BasePort = basePort
	result.Recommendation.Backends = bestBackends
	result.Recommendation.Parallel = bestParallel
	result.Recommendation.Threads = bestThreads
	result.Recommendation.ThreadsBatch = bestThreads
	result.Recommendation.ThreadsHTTP = minInt(8, maxInt(2, bestThreads))
	result.Recommendation.Ctx = ctx
	result.Recommendation.Batch = bestBatch
	result.Recommendation.UBatch = bestUBatch
	result.Notes = []string{
		"Sequential candidate scan prioritized sustained throughput under CPU/memory limits.",
		"Scanner reserves 2 CPU cores and 4 GiB RAM for editor/system responsiveness.",
		fmt.Sprintf("Model memory estimate used: %d GiB (override with LLAMA_MODEL_EST_GIB).", modelEstimateGiB),
	}

	result.EnvPreview = fmt.Sprintf(
		"LLAMA_BASE_PORT=%d\nLLAMA_BACKENDS=%d\nLLAMA_PARALLEL=%d\nLLAMA_THREADS=%d\nLLAMA_THREADS_BATCH=%d\nLLAMA_THREADS_HTTP=%d\nLLAMA_CTX=%d\nLLAMA_BATCH=%d\nLLAMA_UBATCH=%d\n",
		result.Recommendation.BasePort,
		result.Recommendation.Backends,
		result.Recommendation.Parallel,
		result.Recommendation.Threads,
		result.Recommendation.ThreadsBatch,
		result.Recommendation.ThreadsHTTP,
		result.Recommendation.Ctx,
		result.Recommendation.Batch,
		result.Recommendation.UBatch,
	)

	if writeFile {
		envPath := filepath.Join(projectPath, ".engine", "llama-fleet.env")
		if err := os.MkdirAll(filepath.Dir(envPath), 0o755); err != nil {
			return result, err
		}

		content := strings.Builder{}
		content.WriteString("# Generated by Engine fleet scanner. Adjust as needed.\n")
		content.WriteString("# Required model source (edit one):\n")
		content.WriteString("# LLAMA_MODEL_PATH=/absolute/path/to/model.gguf\n")
		content.WriteString("# LLAMA_HF_REPO=owner/repo:quant\n")
		content.WriteString("LLAMA_MODEL_NAME=default\n")
		content.WriteString("LLAMA_HOST=127.0.0.1\n")
		content.WriteString(result.EnvPreview)
		content.WriteString("LLAMA_ROUTER_HOST=127.0.0.1\n")
		content.WriteString("LLAMA_ROUTER_PORT=8080\n")

		if err := os.WriteFile(envPath, []byte(content.String()), 0o644); err != nil {
			return result, err
		}
		result.WroteEnvFile = true
		result.EnvFilePath = envPath
	}

	return result, nil
}

func detectSystemMemoryGiB() int {
	// macOS path.
	if runtime.GOOS == "darwin" {
		out, err := exec.Command("sysctl", "-n", "hw.memsize").Output()
		if err == nil {
			if bytes, parseErr := strconv.ParseInt(strings.TrimSpace(string(out)), 10, 64); parseErr == nil && bytes > 0 {
				return maxInt(1, int(bytes/(1024*1024*1024)))
			}
		}
	}

	// Linux path.
	if runtime.GOOS == "linux" {
		data, err := os.ReadFile("/proc/meminfo")
		if err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				if !strings.HasPrefix(line, "MemTotal:") {
					continue
				}
				fields := strings.Fields(line)
				if len(fields) < 2 {
					continue
				}
				kb, parseErr := strconv.ParseInt(fields[1], 10, 64)
				if parseErr == nil && kb > 0 {
					return maxInt(1, int((kb*1024)/(1024*1024*1024)))
				}
			}
		}
	}

	return 16
}

func parsePositiveIntEnv(key string, fallback int) int {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.Atoi(value)
	if err != nil || parsed <= 0 {
		return fallback
	}
	return parsed
}

func clampInt(v, lo, hi int) int {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func minFloat(a, b float64) float64 {
	if a < b {
		return a
	}
	return b
}

func maxFloat(a, b float64) float64 {
	if a > b {
		return a
	}
	return b
}
