import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  loadConnectionProfiles,
  loadActiveConnectionProfileId,
  loadActiveConnectionProfile,
  saveConnectionProfile,
  deleteConnectionProfile,
  setActiveConnectionProfile,
  clearConnectionProfiles,
  pairConnectionCode,
} from '../connectionProfiles.js';

const PROFILES_KEY = 'engine.connectionProfiles';
const ACTIVE_KEY = 'engine.activeConnectionProfileId';

const makeProfile = (overrides: Partial<Parameters<typeof saveConnectionProfile>[0]> = {}) =>
  saveConnectionProfile({
    name: 'Test Machine',
    host: '10.0.0.1',
    port: '3443',
    workspacePath: '/home/user/project',
    token: 'tok123',
    ...overrides,
  });

describe('connectionProfiles', () => {
  beforeEach(() => {
    window.localStorage.clear();
  });

  afterEach(() => {
    window.localStorage.clear();
  });

  // ─── Load ─────────────────────────────────────────────────────────────────

  describe('loadConnectionProfiles', () => {
    it('NothingStored_EmptyArrayReturned', () => {
      expect(loadConnectionProfiles()).toEqual([]);
    });

    it('ProfilesExist_SortedByUpdatedAtDescending', () => {
      const old = makeProfile({ name: 'Old', updatedAt: '2025-01-01T00:00:00.000Z' });
      const recent = makeProfile({ name: 'Recent', updatedAt: '2026-01-01T00:00:00.000Z' });
      const list = loadConnectionProfiles();
      expect(list[0].id).toBe(recent.id);
      expect(list[1].id).toBe(old.id);
    });
  });

  describe('loadActiveConnectionProfileId', () => {
    it('NothingStored_NullReturned', () => {
      expect(loadActiveConnectionProfileId()).toBeNull();
    });

    it('IdSaved_StoredIdReturned', () => {
      const profile = makeProfile();
      expect(loadActiveConnectionProfileId()).toBe(profile.id);
    });
  });

  describe('loadActiveConnectionProfile', () => {
    it('NoActiveProfile_NullReturned', () => {
      expect(loadActiveConnectionProfile()).toBeNull();
    });

    it('ProfileSaved_MatchingProfileReturned', () => {
      const profile = makeProfile({ name: 'My Server' });
      const active = loadActiveConnectionProfile();
      expect(active?.id).toBe(profile.id);
      expect(active?.name).toBe('My Server');
    });

    it('ActiveIdNoLongerInList_NullReturned', () => {
      window.localStorage.setItem(ACTIVE_KEY, 'ghost-id');
      expect(loadActiveConnectionProfile()).toBeNull();
    });
  });

  // ─── Save ─────────────────────────────────────────────────────────────────

  describe('saveConnectionProfile', () => {
    it('NewProfile_CreatedAndReturned', () => {
      const profile = makeProfile({ name: 'New Box' });
      expect(profile.id).toBeTruthy();
      expect(profile.name).toBe('New Box');
      expect(profile.host).toBe('10.0.0.1');
    });

    it('NoIdSupplied_IdAutoGenerated', () => {
      const profile = makeProfile();
      expect(profile.id.length).toBeGreaterThan(0);
    });

    it('FieldsWithWhitespace_TrimmedOnSave', () => {
      const profile = saveConnectionProfile({
        name: '  Padded  ',
        host: ' 192.168.1.1 ',
        port: ' 3443 ',
        workspacePath: ' /tmp/p ',
        token: ' tok ',
      });
      expect(profile.name).toBe('Padded');
      expect(profile.host).toBe('192.168.1.1');
      expect(profile.port).toBe('3443');
      expect(profile.workspacePath).toBe('/tmp/p');
      expect(profile.token).toBe('tok');
    });

    it('BlankPort_DefaultsTo3443', () => {
      const profile = saveConnectionProfile({
        name: 'X', host: 'x.local', port: '', workspacePath: '/', token: 'tok',
      });
      expect(profile.port).toBe('3443');
    });

    it('BlankName_HostUsedAsName', () => {
      const profile = saveConnectionProfile({
        name: '', host: 'server.local', port: '3443', workspacePath: '/', token: 'tok',
      });
      expect(profile.name).toBe('server.local');
    });

    it('BlankNameAndHost_MachineUsedAsName', () => {
      const profile = saveConnectionProfile({
        name: '', host: '', port: '3443', workspacePath: '/', token: 'tok',
      });
      expect(profile.name).toBe('Machine');
    });

    it('ExistingIdSupplied_ProfileUpdated', () => {
      const original = makeProfile({ name: 'Original' });
      const updated = saveConnectionProfile({ ...original, name: 'Updated' });
      expect(updated.id).toBe(original.id);
      const list = loadConnectionProfiles();
      expect(list.find(p => p.id === original.id)?.name).toBe('Updated');
      expect(list).toHaveLength(1);
    });

    it('ProfileSaved_SetAsActive', () => {
      const profile = makeProfile();
      expect(loadActiveConnectionProfileId()).toBe(profile.id);
    });
  });

  // ─── Delete ───────────────────────────────────────────────────────────────

  describe('deleteConnectionProfile', () => {
    it('TargetProfile_RemovedFromList', () => {
      const profile = makeProfile();
      const remaining = deleteConnectionProfile(profile.id);
      expect(remaining).toHaveLength(0);
      expect(loadConnectionProfiles()).toHaveLength(0);
    });

    it('AfterDeletion_UpdatedListReturned', () => {
      makeProfile({ name: 'A' });
      const b = makeProfile({ name: 'B' });
      const remaining = deleteConnectionProfile(b.id);
      expect(remaining.some(p => p.id === b.id)).toBe(false);
      expect(remaining).toHaveLength(1);
    });

    it('ActiveProfileDeleted_ActiveIdCleared', () => {
      const profile = makeProfile();
      deleteConnectionProfile(profile.id);
      expect(loadActiveConnectionProfileId()).toBeNull();
    });

    it('DifferentProfileDeleted_ActiveIdUnchanged', () => {
      const a = makeProfile({ name: 'A' });
      const b = makeProfile({ name: 'B' });
      const activeId = loadActiveConnectionProfileId();
      deleteConnectionProfile(a.id === activeId ? b.id : a.id);
      expect(loadActiveConnectionProfileId()).toBe(activeId);
    });

    it('ActiveProfileDeleted_SwitchedToNextRemaining', () => {
      const a = makeProfile({ name: 'A' });
      const b = makeProfile({ name: 'B' });
      setActiveConnectionProfile(a.id);
      expect(loadActiveConnectionProfileId()).toBe(a.id);
      const remaining = deleteConnectionProfile(a.id);
      expect(remaining).toHaveLength(1);
      expect(remaining[0].id).toBe(b.id);
      expect(loadActiveConnectionProfileId()).toBe(b.id);
    });
  });

  // ─── Set active ───────────────────────────────────────────────────────────

  describe('setActiveConnectionProfile', () => {
    it('GivenId_PersistedToLocalStorage', () => {
      setActiveConnectionProfile('abc-123');
      expect(window.localStorage.getItem(ACTIVE_KEY)).toBe('abc-123');
    });

    it('NullSupplied_EntryRemoved', () => {
      setActiveConnectionProfile('abc-123');
      setActiveConnectionProfile(null);
      expect(window.localStorage.getItem(ACTIVE_KEY)).toBeNull();
    });
  });

  // ─── Clear ────────────────────────────────────────────────────────────────

  describe('clearConnectionProfiles', () => {
    it('ClearProfiles_BothEntriesRemovedFromStorage', () => {
      makeProfile();
      clearConnectionProfiles();
      expect(window.localStorage.getItem(PROFILES_KEY)).toBeNull();
      expect(window.localStorage.getItem(ACTIVE_KEY)).toBeNull();
      expect(loadConnectionProfiles()).toHaveLength(0);
    });
  });

  // ─── Pairing ──────────────────────────────────────────────────────────────

  describe('pairConnectionCode', () => {
    afterEach(() => {
      vi.restoreAllMocks();
    });

    it('ValidCode_PostsAndReturnsResult', async () => {
      const payload = { ok: true, token: 'desktop-tok', workspacePath: '/home/user' };
      const fetchStub = vi.spyOn(globalThis, 'fetch').mockResolvedValue({
        ok: true,
        json: async () => payload,
      } as Response);

      const result = await pairConnectionCode('engine.dev', '3443', 'ABC-123');
      expect(fetchStub).toHaveBeenCalledWith(
        'https://engine.dev:3443/remote/pair',
        expect.objectContaining({
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ code: 'ABC-123' }),
        }),
      );
      expect(result).toEqual(payload);
    });

    it('ServerNonOkStatus_ErrorObjectReturned', async () => {
      vi.spyOn(globalThis, 'fetch').mockResolvedValue({
        ok: false,
        status: 401,
        json: async () => ({ ok: false, error: 'Invalid code' }),
      } as Response);

      const result = await pairConnectionCode('engine.dev', '3443', 'BAD');
      expect(result.ok).toBe(false);
      expect(result.error).toContain('Invalid code');
    });

    it('ResponseBodyNotJson_GenericErrorReturned', async () => {
      vi.spyOn(globalThis, 'fetch').mockResolvedValue({
        ok: false,
        status: 500,
        json: () => Promise.reject(new Error('not json')),
      } as Response);

      const result = await pairConnectionCode('engine.dev', '3443', 'BAD');
      expect(result.ok).toBe(false);
      expect(typeof result.error).toBe('string');
    });
  });

  // ─── Error paths ──────────────────────────────────────────────────────────

  describe('loadActiveConnectionProfileId — localStorage throws', () => {
    it('LocalStorageGetItemThrows_NullReturned', () => {
      const spy = vi.spyOn(window.localStorage, 'getItem').mockImplementation(() => {
        throw new Error('storage quota exceeded');
      });
      expect(loadActiveConnectionProfileId()).toBeNull();
      spy.mockRestore();
    });
  });

  describe('saveConnectionProfile — localStorage.setItem throws', () => {
    it('SetItemThrows_ProfileReturnedWithoutPersisting', () => {
      const spy = vi.spyOn(window.localStorage, 'setItem').mockImplementation(() => {
        throw new Error('storage quota exceeded');
      });
      const profile = saveConnectionProfile({
        name: 'Failing Machine',
        host: '10.0.0.2',
        port: '3443',
        workspacePath: '/home',
        token: 'tok',
      });
      spy.mockRestore();
      expect(profile.name).toBe('Failing Machine');
    });
  });
});
